project:
  type: website
  output-dir: docs

website:
  title: "Elijah Peake's Website Warmup"
  site-path: "/warmup-elijah-peake/"
  favicon: images/image0.jpg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About 
      - href: articles/index.qmd
        text: Articles
      - href: posts/index.qmd
        text: Blog
 
sidebar:
    - id: none
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - section: "Articles"
          href: articles/index.qmd
          contents: 
            - text: "Making a table"
              href:  articles/article_01.qmd
            - text: "Sorting a table"
              href:  articles/article_02.qmd
        - section: "Posts"
          href: posts/index.qmd
          contents: "posts/*/*.qmd"
          sort:
            - "date desc"




format:
  html:
    theme: minty
    css: styles.css
    toc: true



