project:
  type: website
  output-dir: docs

website:
  title: "Elijah Peake's Website Warmup"
  site-path: "/warmup-elijah-peake/"
  favicon: images/image0.jpg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About 
      - href: articles/index.qmd
        text: Articles
        menu:
          - href: articles/index.qmd
            text: "Articles"
          - href: articles/article_01.qmd
            text: "Making a table"
          - href: articles/article_02.qmd
            text: "Sorting a table"
          - href: articles/article_03.qmd
            text: "Major Enhancement"
      - text: Blog
        menu: 
          - href: posts/index.qmd
            text: "Blog"
          - href: posts/2023-11-10
            text: "Benefits of Snap"
          - href: posts/2023-11-11
            text: "Favicon minor enhancement"
          - href: posts/2023-11-12
            text: "Larum Ipsum 1"
          - href: posts/2023-11-13
            text: "Larum Ipsum 2"
          - href: posts/2023-11-14
            text: "Larum Ipsum 3"


 




format:
  html:
    theme: custom.scss
    css: styles.css
    toc: true



