project:
  type: website
  output-dir: docs

website:
  title: "Elijah Peake's Website Warmup"
  site-path: "/warmup-elijah-peake/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About 
      - href: articles/index.qmd
        text: Articles
 
  sidebar:
    - id: articles
      title: "Articles"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
       - text: "Making a Table"
         href: articles/article_01.qmd
       - text: "Sorting a Table"
         href: articles/article_02.qmd


format:
  html:
    theme: flatly
    css: styles.css
    toc: true



