---
title: "Making a Table"
---

## Intro to the problem
This essay will explain a JavaScript code snippet that populates a table with artist data. The code snippet provided demonstrates how to use JavaScript to select a table and dynamically insert rows of artist information into it. 

## The Data
The code begins with the definition of an array named "artists." This array stores information about five different artists. Each artist object has three properties: "name," "birthYear," and "link."
```{filename="input.txt"}
const artists = [
   {
     name: "Ms Scandalous",
     birthYear: 1985,
     link: "https://www.youtube.com/watch?v=2FPivlfvxu0"
   },
   {
    name: "Juggy D",
    birthYear: 1981,
    link: "https://www.youtube.com/watch?v=1jAc_-FVjdI"
  },
  {
    name: "Sukhbir Singh",
    birthYear: 1969,
    link: "https://www.youtube.com/watch?v=HiprNF9Jad0"
  },
  {
    name: "Abrar-ul-Haq",
    birthYear: 1989,
    link: "https://www.youtube.com/watch?v=-lnnVIP7FEc"
  },
  {
    name: "Rishi Rich",
    birthYear: 1970,
    link: "https://www.youtube.com/watch?v=O95-w2gACuA"
  }
 ]
```

We will be taking this data from the array and will be putting it into a table.

## Creating the Table
We start off by creating the table by using this code line.
```js
const table = document.getElementById("bhangra");
```

## Creating the labels
In order to help identify each section of the table the header provides useful information for each data point.
```{filename="input.txt"}
const labels = table.createTHead();
labels.innerHTML = "<tr><th>Name</th><th>Birth Year</th><th>Link</th></tr>";
```

## Populating the table
Now, we get to actually filling the table with data. We use the code `artists.forEach` loop.

It's like making a list, and for each artist in our list (the "artists" array), we do the same thing: 

We create a new row to represent each artist, and we call it "newRow." It's like adding a new line to our list.

Inside that new row, create three cells to put the artist's details. Label the names: "nameCell," "birthYearCell," and "linkCell." These cells are separate columns in our list.

In the "nameCell," write down the artist's name. In the "birthYearCell," put their birth year. And in the "linkCell," add a link to their YouTube video. So, we're filling in our list with the artist's name, birth year, and a link to their video.

```{filename="input.txt"}
artists.forEach((artist) => {
  const newRow = table.insertRow();
  const nameCell = newRow.insertCell(0);
  const birthYearCell = newRow.insertCell(1);
  const linkCell = newRow.insertCell(2);

  nameCell.innerText = artist.name;
  birthYearCell.innerText = artist.birthYear;
  linkCell.innerHTML = `<a href="${artist.link}" target="_blank">${artist.link}</a>`;
});
```

We do this for every artist in our list, and as we go through the loop, we keep adding new rows with the artist's details. It's building our list one artist at a time.

So, this loop helps us create a table with all the artists and their information; making the table complete.

## Full code
```{.javascript filename="table-assign.js"}
  const table = document.getElementById("bhangra");
 
 
  const labels = table.createTHead();
  labels.innerHTML = "<tr><th>Name</th><th>Birth Year</th><th>Link</th></tr>";
  
  artists.forEach((artist) => {
    const newRow = table.insertRow();
    const nameCell = newRow.insertCell(0);
    const birthYearCell = newRow.insertCell(1);
    const linkCell = newRow.insertCell(2);
  
    nameCell.innerText = artist.name;
    birthYearCell.innerText = artist.birthYear;
    linkCell.innerHTML = `<a href="${artist.link}" target="_blank">${artist.link}</a>`;
  });
  ```
