---
title: Major Enhancement
---

The major enhancement I decided to do was to customize my css files. The changes that i made include making a custome theme for my navbar as well as changing how the words look.

## The Color for the navbar

The color I chose for thr navbar was a shade of red.

```.js
.navbar {
  background-color: rgb(184, 29, 81);
}
```

## The styling for the navbar
The code below modifies the words on the navbar.

```.js
.navbar {
  font-family: 'Arial', sans-serif;
  font-weight: bold;
  font-style: italic;
  font-weight: normal;
  font-size: 16px;
  line-height: 1.5;
}
```
* `font-family`- This code changes the font for the text to Arial.
* `font-weight` - Changes the text to become bold
* `font-style` - Changes the text so it becomes italicied
* `font-size` - changes the font size so it becomes 16 pixels
* `line-height` - defines the space between the navbar and the text

# Underlining and Alignment 

```.js
.navbar{
  text-decoration: underline; 
  text-align: left;
}
```

* `text-decoration: underline`- This adds an underline to the text in the navbar.
* ` text-align: left;`- This aligns all of the text in the navbar to the left

## Drop down Menu
The drop down menu allows for easy access to pages on the website and helps to keep things better organized and clean. Implementing the drop down menu looks something like this.
```.js
 - text: Articles
        menu:
          - href: articles/index.qmd
            text: "Articles"
          - href: articles/article_01.qmd
            text: "Making a table"
          - href: articles/article_02.qmd
            text: "Sorting a table"
          - href: articles/article_03.qmd
            text: "Major Enhancement"
      - text: Blog
        menu: 
          - href: posts/index.qmd
            text: "Blog"
          - href: posts/2023-11-10
            text: "Benefits of Snap"
          - href: posts/2023-11-11
            text: "Favicon minor enhancement"
          - href: posts/2023-11-12
            text: "Larum Ipsum 1"
          - href: posts/2023-11-13
            text: "Larum Ipsum 2"
          - href: posts/2023-11-14
            text: "Larum Ipsum 3"
```
I added `menu` into the `quarto.yml`under the `blog` and `articles` section in order to make the drop down menus. Doing this makes a drop down menu when you click on either blog or Articles.


